/*  MY NAME=Gaoxiang Chen MY ID=GAC69
		
		CORRECT OUTPUT 5 PTS	 CORRECT EXPLANATION 2 POINTS
--------------------------------------------------------------------------
MYSTERY #1:  (1) output = 951413				(2) PRINT THE REVERSE OF TARGET NUMBER
MYSTERY #2:  (1) output = 23					(2) SUM OF ALL DIGITS IN TARGET NUMBER
MYSTERY #3:  (1) output = 23					(2) SUM OF THE ARR VALUES
MYSTERY #4:  (1) output = false					(2) COMPARE THE FIRST AND SECOND VALUES OF THE ARR
MYSTERY #5:  (1) output = 5 4 3 2 1				(2) PRINT N TO 1, WITH EACH NUMBER FOLLOWED BY A SPACE
MYSTERY #6:  (1) output = 1 2 3 4 5				(2) PRINT 1 TO N, WITH EACH NUMBER FOLLOWED BY A SPACE
MYSTERY #7:  (1) output = 5 4 3 2 1 1 2 3 4 5	(2) PRINT N TO 1 AND 1 TO N, WITH EACH NUMBER FOLLOWED BY A SPACE
*/
